### ISSUE TITLE
Bust all cache with params

### ISSUE THREAD

**Issue by mandarvl** [BJS-kr/nestjs-omacache#1]
I'm caching some data with params like this :
```
@InMemoryCache({
        key: 'inventories',
        kind: 'temporal',
        ttl: 60 * 30,
        paramIndex: [0, 1]
 })
getInventories(p1:  string, p2: number) {
 // return inventories based on params
}
```

Now when updating inventories, How can I bust all cached data with the key **inventories** ?
For example: 
```
@InMemoryCache({
        key: 'inventories',
        kind: 'bust',
       allParams: true
 })
```

**Comment by BJS-kr** [comment]
I'll work on it. Thanks for the suggestion

**Comment by mandarvl** [comment]
Thank you, great package by the way!

**Comment by BJS-kr** [comment]
This task was assigned to member today. Feature will be added next monday. Thanks for waiting!

**Comment by mandarvl** [comment]
> This task was assigned to member today. Feature will be added next monday. Thanks for waiting!

Glad to hear that

**Comment by BJS-kr** [comment]
feature added! thanks for your patience. closing issue

**Comment by mandarvl** [comment]
I updated the package to 1.0.2 and it gives me this error when I try to use the `bustAllChildren` option.

```
Argument of type '{ key: string; kind: "bust"; bustAllChildren: boolean; }' is not assignable to parameter of type 'CacheOptions<"bust">'.
  Object literal may only specify known properties, and 'bustAllChildren' does not exist in type 'CacheOptions<"bust">'
```
