### ISSUE TITLE
Update reflect-metadata version on peer deps.

### ISSUE THREAD

**Issue by alaadotsol** [BJS-kr/nestjs-omacache#26]
## Issue

Current `reflect-metadata` version used in peer dependencies is outdated

https://github.com/BJS-kr/nestjs-omacache/blob/1aef658dd71a2b9701f6522958caf6ee61b99b65/package.json#L38

## Proposed Solution

* Upgrade peer deps to match latest major version of `reflect-metadata` -> `0.2.2` preferably.
* Mention in peer deps that both 1.x and 2.x are both supported (which is the case I assume?)

## Why?

* Projects made today with new version will keep getting warn prompts:
```
 WARN  Issues with peer dependencies found
my-project-ts
└─┬ nestjs-omacache 1.1.3
  └── ✕ unmet peer reflect-metadata@^0.1.12: found 0.2.2
```
* https://github.com/rbuckton/reflect-metadata/compare/v0.1.14...release-0.2

**Comment by BJS-kr** [comment]
got it!

**Comment by BJS-kr** [comment]
I updated package. please tell me if anything wrong. I'll close the issue if there are no problems

**Comment by alaadotsol** [comment]
All good, thanks for the quick solve! Reference: https://github.com/BJS-kr/nestjs-omacache/pull/27
