### ISSUE TITLE
bust multiple cache keys

### ISSUE THREAD

**Issue by jsbyeon1** [BJS-kr/nestjs-omacache#3]
When a data changed, there should be multiple routes affected by the change

i.e.) When User info changed: User, MyPage, Profile routes should remove their cache immediately

it can improve control over cache much more easily

**Comment by mandarvl** [comment]
You can bust a specific key using this options:
```
{
  key: 'users',
  kind: 'bust'
}
```

The only problem is that it doesn't bust all childs cache (ie with params) but there's already a pull request for this feature
