### ISSUE TITLE
Empty package in npm

### ISSUE THREAD

**Issue by mandarvl** [BJS-kr/nestjs-omacache#33]
When trying to install the latest version of this package i.e 1.1.5, I get empty package in node_modules.

After checking the code in [npm](https://www.npmjs.com/package/nestjs-omacache?activeTab=code), I see that it does not contain the build files.

**Comment by BJS-kr** [comment]
Sorry for mistake. Will fix this right away

**Comment by BJS-kr** [comment]
fixed at 1.1.6. thank you for your continuous watching. I really appreciate it.
