### ISSUE TITLE
BustAllChildren does not exist in type CacheOptions

### ISSUE THREAD

**Issue by mandarvl** [BJS-kr/nestjs-omacache#5]
I updated the package to 1.0.2 and it gives me this error when I try to use the `bustAllChildren` option.

```
Argument of type '{ key: string; kind: "bust"; bustAllChildren: boolean; }' is not assignable to parameter of type 'CacheOptions<"bust">'.
  Object literal may only specify known properties, and 'bustAllChildren' does not exist in type 'CacheOptions<"bust">'
```

I think it's because the code in npm package is not updated yet

**Comment by jsbyeon1** [comment]
oh sorry I'll fix it right away!

**Comment by jsbyeon1** [comment]
It now has been fixed. the problem was publish process. source was changed, but not compiled to changed version
thanks for your patience
