### ISSUE TITLE
Handle null parameters value

### ISSUE THREAD

**Issue by mandarvl** [BJS-kr/nestjs-omacache#6]
I have this method in my controller :

```
@InMemoryCache({
    key: 'facilities',
    kind: 'temporal',
    ttl: 60 * 60 * 10,
    paramIndex: [0]
 })
async loadData(@Query('someParam') param?: number) {
 ...
}
```

The problem is that when userId is null (or undefined), it throw this error :
`TypeError : The first argument must be of type string or an instance of Buffer, ArrayBuffer, or Array or an Array-like Object. Received null`

Is it possible to allow optional parameters ?

**Comment by BJS-kr** [comment]
Of course! I think recent update brought this bug. I'll fix it

**Comment by BJS-kr** [comment]
once you update package version to 1.0.5, you'll get fixed package. thanks for contribution!

**Comment by mandarvl** [comment]
Thank you, will try it asap!
